### ISSUE TITLE
Where to find 'y_test' and 'X_test' files?

### ISSUE THREAD

**Issue by Yutong-Y** [alonsaguy/DBlink#1]
Hi, I'm interested in your DBlink paper and want to try your model. You said you supplied three files to run the demo but I couldn't find the 'y_test' and 'X_test' file. Could you please provide these files? Thank you!

**Comment by Yutong-Y** [comment]
Sorry I just realised they could be generated. Thanks!

**Comment by alonsaguy** [comment]
Hi,

I am sorry for not responding earlier, I have been over my head with other
tasks.

I hope things are working out for you, and if you have any further
questions please do not hesitate to contact me.

Best,
Alon
